//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApp.RobotArmServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RobotArmState", Namespace="http://schemas.datacontract.org/2004/07/SnusProject.Models")]
    [System.SerializableAttribute()]
    public partial class RobotArmState : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AngleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Angle {
            get {
                return this.AngleField;
            }
            set {
                if ((this.AngleField.Equals(value) != true)) {
                    this.AngleField = value;
                    this.RaisePropertyChanged("Angle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RobotArmServiceReference.IRobotArmService")]
    public interface IRobotArmService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/EnqueueMoveLeft", ReplyAction="http://tempuri.org/IRobotArmService/EnqueueMoveLeftResponse")]
        void EnqueueMoveLeft(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/EnqueueMoveLeft", ReplyAction="http://tempuri.org/IRobotArmService/EnqueueMoveLeftResponse")]
        System.Threading.Tasks.Task EnqueueMoveLeftAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/EnqueueMoveRight", ReplyAction="http://tempuri.org/IRobotArmService/EnqueueMoveRightResponse")]
        void EnqueueMoveRight(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/EnqueueMoveRight", ReplyAction="http://tempuri.org/IRobotArmService/EnqueueMoveRightResponse")]
        System.Threading.Tasks.Task EnqueueMoveRightAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/EnqueueMoveUp", ReplyAction="http://tempuri.org/IRobotArmService/EnqueueMoveUpResponse")]
        void EnqueueMoveUp(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/EnqueueMoveUp", ReplyAction="http://tempuri.org/IRobotArmService/EnqueueMoveUpResponse")]
        System.Threading.Tasks.Task EnqueueMoveUpAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/EnqueueMoveDown", ReplyAction="http://tempuri.org/IRobotArmService/EnqueueMoveDownResponse")]
        void EnqueueMoveDown(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/EnqueueMoveDown", ReplyAction="http://tempuri.org/IRobotArmService/EnqueueMoveDownResponse")]
        System.Threading.Tasks.Task EnqueueMoveDownAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/EnqueueRotate", ReplyAction="http://tempuri.org/IRobotArmService/EnqueueRotateResponse")]
        void EnqueueRotate(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/EnqueueRotate", ReplyAction="http://tempuri.org/IRobotArmService/EnqueueRotateResponse")]
        System.Threading.Tasks.Task EnqueueRotateAsync(int clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/GetCurrentState", ReplyAction="http://tempuri.org/IRobotArmService/GetCurrentStateResponse")]
        ClientApp.RobotArmServiceReference.RobotArmState GetCurrentState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRobotArmService/GetCurrentState", ReplyAction="http://tempuri.org/IRobotArmService/GetCurrentStateResponse")]
        System.Threading.Tasks.Task<ClientApp.RobotArmServiceReference.RobotArmState> GetCurrentStateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRobotArmServiceChannel : ClientApp.RobotArmServiceReference.IRobotArmService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RobotArmServiceClient : System.ServiceModel.ClientBase<ClientApp.RobotArmServiceReference.IRobotArmService>, ClientApp.RobotArmServiceReference.IRobotArmService {
        
        public RobotArmServiceClient() {
        }
        
        public RobotArmServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RobotArmServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RobotArmServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RobotArmServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void EnqueueMoveLeft(int clientId) {
            base.Channel.EnqueueMoveLeft(clientId);
        }
        
        public System.Threading.Tasks.Task EnqueueMoveLeftAsync(int clientId) {
            return base.Channel.EnqueueMoveLeftAsync(clientId);
        }
        
        public void EnqueueMoveRight(int clientId) {
            base.Channel.EnqueueMoveRight(clientId);
        }
        
        public System.Threading.Tasks.Task EnqueueMoveRightAsync(int clientId) {
            return base.Channel.EnqueueMoveRightAsync(clientId);
        }
        
        public void EnqueueMoveUp(int clientId) {
            base.Channel.EnqueueMoveUp(clientId);
        }
        
        public System.Threading.Tasks.Task EnqueueMoveUpAsync(int clientId) {
            return base.Channel.EnqueueMoveUpAsync(clientId);
        }
        
        public void EnqueueMoveDown(int clientId) {
            base.Channel.EnqueueMoveDown(clientId);
        }
        
        public System.Threading.Tasks.Task EnqueueMoveDownAsync(int clientId) {
            return base.Channel.EnqueueMoveDownAsync(clientId);
        }
        
        public void EnqueueRotate(int clientId) {
            base.Channel.EnqueueRotate(clientId);
        }
        
        public System.Threading.Tasks.Task EnqueueRotateAsync(int clientId) {
            return base.Channel.EnqueueRotateAsync(clientId);
        }
        
        public ClientApp.RobotArmServiceReference.RobotArmState GetCurrentState() {
            return base.Channel.GetCurrentState();
        }
        
        public System.Threading.Tasks.Task<ClientApp.RobotArmServiceReference.RobotArmState> GetCurrentStateAsync() {
            return base.Channel.GetCurrentStateAsync();
        }
    }
}
